import type { Translations, CVData, LanguageOption } from './types';

export const languageOptions: LanguageOption[] = [
    { code: 'en', name: 'EN', flag: '🇺🇸' },
    { code: 'es', name: 'ES', flag: '🇪🇸' },
    { code: 'fr', name: 'FR', flag: '🇫🇷' },
    { code: 'tr', name: 'TR', flag: '🇹🇷' },
    { code: 'it', name: 'IT', flag: '🇮🇹' },
    { code: 'th', name: 'TH', flag: '🇹🇭' },
    { code: 'zh', name: 'ZH', flag: '🇨🇳' },
    { code: 'ar', name: 'AR', flag: '🇸🇦' },
    { code: 'de', name: 'DE', flag: '🇩🇪' },
];

export const cvData: CVData = {
    experience: [
        {
            titleKey: "job1_title",
            companyKey: "UWC Thailand",
            locationKey: "job1_location",
            dateKey: "08/2025 - 10/2025",
            descriptionKeys: ["job1_desc1"],
            icon: "fas fa-graduation-cap",
            current: true,
        },
        {
            titleKey: "job2_title",
            companyKey: "Tarsus American College",
            locationKey: "job2_location",
            dateKey: "11/2021 - 07/2023",
            descriptionKeys: ["job2_desc1", "job2_desc2", "job2_desc3", "job2_desc4"],
            icon: "fas fa-chalkboard-teacher",
        },
        {
            titleKey: "job3_title",
            companyKey: "Colegio Alvernia Bilingüe",
            locationKey: "job3_location",
            dateKey: "01/2020 - 07/2021",
            descriptionKeys: ["job3_desc1", "job3_desc2", "job3_desc3"],
            icon: "fas fa-globe-americas",
        },
        {
            titleKey: "job4_title",
            companyKey: "Vicariato Apostólico de Inírida",
            locationKey: "job4_location",
            dateKey: "04/2019 - 09/2019",
            descriptionKeys: ["job4_desc1"],
            icon: "fas fa-heart",
        },
    ],
    education: [
        {
            degreeKey: "edu1_title",
            institutionKey: "Universidad Camilo José Cela",
            locationKey: "edu1_location",
            dateKey: "09/2025",
            icon: "fas fa-certificate",
            current: true,
        },
        {
            degreeKey: "edu2_title",
            institutionKey: "Universidad Camilo José Cela",
            locationKey: "edu2_location",
            dateKey: "09/2025",
            icon: "fas fa-globe",
        },
        {
            degreeKey: "edu3_title",
            institutionKey: "Universidad de Sevilla",
            locationKey: "edu3_location",
            dateKey: "06/2024",
            icon: "fas fa-graduation-cap",
        },
        {
            degreeKey: "edu4_title",
            institutionKey: "Universidad Pedagógica Nacional",
            locationKey: "edu4_location",
            dateKey: "11/2018",
            icon: "fas fa-book-open",
        },
    ],
    skills: [
        {
            titleKey: "skills_soft_title",
            icon: "fas fa-heart",
            skills: [
                { nameKey: "skill_adaptability", percentage: 95 },
                { nameKey: "skill_empathy", percentage: 90 },
                { nameKey: "skill_cultural", percentage: 88 },
                { nameKey: "skill_teamwork", percentage: 92 },
                { nameKey: "skill_resilience", percentage: 85 },
                { nameKey: "skill_proactiveness", percentage: 87 },
                { nameKey: "skill_creativity", percentage: 89 },
            ],
        },
        {
            titleKey: "skills_tech_title",
            icon: "fas fa-laptop-code",
            skills: [
                { nameKey: "ManageBac", percentage: 85 },
                { nameKey: "Canvas Instructure", percentage: 80 },
                { nameKey: "Blackboard", percentage: 75 },
                { nameKey: "Moodle", percentage: 78 },
                { nameKey: "H5P", percentage: 90 },
                { nameKey: "Python 3", percentage: 70 },
                { nameKey: "WordPress", percentage: 82 },
                { nameKey: "HTML", percentage: 88 },
                { nameKey: "CSS", percentage: 85 },
                { nameKey: "JavaScript", percentage: 75 },
            ],
        },
    ],
    languages: [
        { nameKey: "lang_spanish", levelKey: "lang_spanish_level", levelClass: "native", flag: "🇪🇸" },
        { nameKey: "lang_english", levelKey: "lang_english_level", levelClass: "advanced", flag: "🇬🇧" },
        { nameKey: "lang_french", levelKey: "lang_french_level", levelClass: "intermediate", flag: "🇫🇷" },
        { nameKey: "lang_turkish", levelKey: "lang_turkish_level", levelClass: "beginner", flag: "🇹🇷" },
    ],
};

export const translations: Translations = {
    ar: {
        "nav_profile": "الملف الشخصي", "nav_experience": "الخبرة", "nav_education": "التعليم", "nav_skills": "المهارات", "nav_languages": "اللغات",
        "print_btn_text": "PDF", "contact_btn_text": "معلومات الاتصال", "contact_title": "معلومات الاتصال", "contact_location_label": "الموقع",
        "contact_email_label": "البريد الإلكتروني", "contact_phone_spain_label": "الهاتف (إسبانيا)", "contact_phone_thailand_label": "الهاتف (تايلاند)",
        "linkedin_btn_text": "عرض الملف الشخصي على LinkedIn", "profile_title": "الملف الشخصي",
        "profile_text": "بخلفية دولية في تعليم اللغات، أسترشد بنهج شمولي لتصميم دروس تدمج الأبعاد الاجتماعية والعاطفية والمعرفية والثقافية للتعلم. مستوحاة من قيم الاحترام والرحمة والنزاهة، أسعى جاهدة لخلق بيئات تعليمية شاملة ومستجيبة ثقافيًا تحتفي بالروابط متعددة الثقافات وتعزز الشعور بالمواطنة العالمية.",
        "experience_title": "الخبرة العملية", "job1_title": "مدرس اللغة الإسبانية ووجهات النظر العالمية في برنامج MYP",
        "job1_desc1": "تصميم وتقديم وحدات الاستقصاء للغة الإسبانية ووجهات النظر العالمية في برنامج MYP، مع تطبيق إطار برنامج MYP التابع للبكالوريا الدولية لتعزيز التفكير النقدي والعقلية الدولية.",
        "job2_title": "مدرس لغة إسبانية", "job2_desc1": "تخطيط وتقديم منهج اللغة الإسبانية لأكثر من 80 طالباً في المرحلة الإعدادية والصف التاسع (المستوى A1-A2).",
        "job2_desc2": "تطوير موارد تعليمية تفاعلية (+30) باستخدام H5P و HTML/CSS، مما حقق تحسناً ملحوظاً في مشاركة الطلاب.",
        "job2_desc3": "قيادة تنظيم الفعاليات الثقافية مثل يوم اللغة لتعزيز تعدد اللغات في المجتمع المدرسي.",
        "job2_desc4": "التعاون النشط في التحضير واللوجستيات لاعتماد المركز كموقع رسمي لامتحانات DELE.",
        "job3_title": "مدرس التواصل والعالم متعدد الثقافات", "job3_desc1": "تدريس اللغة الإنجليزية لأكثر من 120 طالباً في المدارس الثانوية، مع تحقيق تحسن قابل للقياس في الكفاءات التواصلية (المستويات A1-B2).",
        "job3_desc2": "تنفيذ أنظمة التقييم التكويني والختامي، باستخدام منصات LMS لتحسين التغذية الراجعة للطلاب.",
        "job3_desc3": "الإشراف وتوجيه مشروع بيئي متعدد التخصصات، مع دمج أهداف تعلم اللغة مع الوعي البيئي.",
        "job4_title": "مدرس لغة إسبانية وإنجليزية", "job4_desc1": "تكييف منهج اللغات للمدارس الابتدائية والثانوية مع نهج 'التعليم القائم على المكان'، وربط التعلم بالبيئة الثقافية والطبيعية المحلية.",
        "education_title": "التعليم", "edu1_title": "شهادة البكالوريا الدولية في التدريس والتعلم", "edu2_title": "دبلوم التخصص في التعليم الدولي",
        "edu3_title": "درجة الماجستير في تدريس اللغة الإسبانية (ELE)", "edu4_title": "بكالوريوس التربية في اللغة الإسبانية واللغات الأجنبية",
        "skills_title": "المهارات الأساسية", "skills_soft_title": "المهارات الشخصية", "skill_adaptability": "القدرة على التكيف", "skill_empathy": "التعاطف والصبر",
        "skill_cultural": "الوعي متعدد الثقافات", "skill_teamwork": "العمل الجماعي", "skill_resilience": "المرونة", "skill_proactiveness": "المبادرة",
        "skill_creativity": "الإبداع", "skills_tech_title": "التقنيات والمنصات", "languages_title": "اللغات", "lang_spanish": "الإسبانية",
        "lang_spanish_level": "اللغة الأم", "lang_english": "الإنجليزية", "lang_english_level": "متقدم (C1)", "lang_french": "الفرنسية",
        "lang_french_level": "فوق المتوسط (B2)", "lang_turkish": "التركية", "lang_turkish_level": "مبتدئ", "job1_location": "UWC Thailand | Thalang, Thailand 🇹🇭",
        "job2_location": "Tarsus American College | Tarsus, Türkiye 🇹🇷", "job3_location": "Colegio Alvernia Bilingüe | Bogotá, Colombia 🇨🇴",
        "job4_location": "Vicariato Apostólico de Inírida | Guainía, Colombia 🇨🇴", "edu1_location": "Universidad Camilo José Cela | Spain 🇪🇸",
        "edu2_location": "Universidad Camilo José Cela | Spain 🇪🇸", "edu3_location": "Universidad de Sevilla | Spain 🇪🇸",
        "edu4_location": "Universidad Pedagógica Nacional | Colombia 🇨🇴", "read_more": "اقرأ المزيد", "read_less": "اقرأ أقل",
        "loading_language": "جار تحميل اللغة...", "last_updated": "آخر تحديث:", "back_to_top": "العودة إلى الأعلى", "focus_mode": "وضع التركيز",
        "high_contrast": "تباين عال",
        "profile_approach_title": "نهج شمولي للتدريس"
    },
    de: {
        "nav_profile": "Profil", "nav_experience": "Erfahrung", "nav_education": "Bildung", "nav_skills": "Fähigkeiten", "nav_languages": "Sprachen",
        "print_btn_text": "PDF", "contact_btn_text": "Kontaktinformationen", "contact_title": "Kontaktinformationen", "contact_location_label": "Standort",
        "contact_email_label": "E-Mail", "contact_phone_spain_label": "Telefon (Spanien)", "contact_phone_thailand_label": "Telefon (Thailand)",
        "linkedin_btn_text": "LinkedIn-Profil anzeigen", "profile_title": "Berufliches Profil",
        "profile_text": "Mit einem internationalen Hintergrund im Sprachunterricht verfolge ich einen ganzheitlichen Ansatz, um Unterrichtsstunden zu gestalten, die die sozialen, emotionalen, kognitiven und kulturellen Dimensionen des Lernens integrieren. Inspiriert von den Werten Respekt, Mitgefühl und Integrität strebe ich danach, inklusive und kulturell ansprechende Lernumgebungen zu schaffen, die multikulturelle Verbindungen feiern und ein Gefühl der globalen Bürgerschaft fördern.",
        "experience_title": "Berufserfahrung", "job1_title": "MYP Spanisch & Globale Perspektiven Lehrer",
        "job1_desc1": "Entwerfen und Durchführen von Erkundungseinheiten für MYP-Spanisch und Globale Perspektiven, Anwendung des IB MYP-Rahmens zur Förderung kritischen Denkens und internationaler Gesinnung.",
        "job2_title": "Spanischlehrer", "job2_desc1": "Planen und Durchführen des Spanisch-Curriculums für über 80 Vorbereitungs- und 9. Klassen-Schüler (A1-A2 Niveau).",
        "job2_desc2": "Entwicklung interaktiver Bildungsressourcen (+30) mit H5P und HTML/CSS, Erreichen einer bemerkenswerten Verbesserung des Schülerengagements.",
        "job2_desc3": "Leitung der Organisation kultureller Veranstaltungen wie dem Tag der Sprachen zur Förderung der Mehrsprachigkeit in der Schulgemeinschaft.",
        "job2_desc4": "Aktive Zusammenarbeit bei der Vorbereitung und Logistik für die Akkreditierung des Zentrums als offizieller DELE-Prüfungsort.",
        "job3_title": "Lehrer für Kommunikation & Interkulturelle Welt", "job3_desc1": "Englischunterricht für über 120 Sekundarschüler, Erreichen einer messbaren Verbesserung der kommunikativen Kompetenzen (A1-B2 Niveaus).",
        "job3_desc2": "Implementierung formativer und summativer Bewertungssysteme, Nutzung von LMS-Plattformen zur Optimierung des Schülerfeedbacks.",
        "job3_desc3": "Betreuung und Anleitung eines fächerübergreifenden Umweltprojekts, Integration von Sprachlernzielen mit ökologischem Bewusstsein.",
        "job4_title": "Spanisch- und Englischlehrer", "job4_desc1": "Anpassung des Sprachcurriculums für Grund- und Sekundarschulen an einen 'ortsbezogenen Bildungsansatz', Verbindung des Lernens mit der lokalen kulturellen und natürlichen Umwelt.",
        "education_title": "Bildung", "edu1_title": "IB-Zertifikat in Lehren und Lernen", "edu2_title": "Spezialisierungsdiplom in Internationaler Bildung",
        "edu3_title": "Master-Abschluss im Unterrichten von Spanisch (ELE)", "edu4_title": "Bachelor of Education in Spanisch und Fremdsprachen",
        "skills_title": "Schlüsselfähigkeiten", "skills_soft_title": "Soft Skills", "skill_adaptability": "Anpassungsfähigkeit", "skill_empathy": "Empathie & Geduld",
        "skill_cultural": "Interkulturelles Bewusstsein", "skill_teamwork": "Teamfähigkeit", "skill_resilience": "Belastbarkeit", "skill_proactiveness": "Eigeninitiative",
        "skill_creativity": "Kreativität", "skills_tech_title": "Technologien & Plattformen", "languages_title": "Sprachen", "lang_spanish": "Spanisch",
        "lang_spanish_level": "Muttersprache", "lang_english": "Englisch", "lang_english_level": "Fortgeschritten (C1)", "lang_french": "Französisch",
        "lang_french_level": "Obere Mittelstufe (B2)", "lang_turkish": "Türkisch", "lang_turkish_level": "Anfänger",
        "job1_location": "UWC Thailand | Thalang, Thailand 🇹🇭", "job2_location": "Tarsus American College | Tarsus, Türkiye 🇹🇷", "job3_location": "Colegio Alvernia Bilingüe | Bogotá, Colombia 🇨🇴",
        "job4_location": "Vicariato Apostólico de Inírida | Guainía, Colombia 🇨🇴", "edu1_location": "Universidad Camilo José Cela | Spain 🇪🇸", "edu2_location": "Universidad Camilo José Cela | Spain 🇪🇸",
        "edu3_location": "Universidad de Sevilla | Spain 🇪🇸", "edu4_location": "Universidad Pedagógica Nacional | Colombia 🇨🇴", "read_more": "Mehr lesen", "read_less": "Weniger lesen",
        "loading_language": "Sprache wird geladen...", "last_updated": "Zuletzt aktualisiert:", "back_to_top": "Nach oben", "focus_mode": "Fokusmodus", "high_contrast": "Hoher Kontrast",
        "profile_approach_title": "Ganzheitlicher Lehransatz"
    },
    en: {
        "nav_profile": "Profile", "nav_experience": "Experience", "nav_education": "Education", "nav_skills": "Skills", "nav_languages": "Languages",
        "print_btn_text": "PDF", "contact_btn_text": "Contact Info", "contact_title": "Contact Information", "contact_location_label": "Location",
        "contact_email_label": "Email", "contact_phone_spain_label": "Phone (Spain)", "contact_phone_thailand_label": "Phone (Thailand)",
        "linkedin_btn_text": "View LinkedIn Profile", "profile_title": "Profile",
        "profile_approach_title": "Holistic Teaching Approach",
        "profile_text": "With an international background in language education, I am guided by a holistic approach to design lessons that integrate the social, emotional, cognitive, and cultural dimensions of learning. Inspired by the values of respect, compassion, and integrity, I strive to create inclusive and culturally responsive learning environments that celebrate multicultural connections and foster a sense of global citizenship.",
        "profile_international_title": "International Experience", "profile_international_desc": "Teaching across multiple countries and cultures",
        "profile_values_title": "Core Values", "profile_values_desc": "Respect, compassion, and integrity-driven education",
        "profile_inclusive_title": "Inclusive Learning", "profile_inclusive_desc": "Creating culturally responsive environments",
        "experience_title": "Work Experience", "job1_title": "MYP Spanish & Global Perspectives Teacher",
        "job1_desc1": "Design and deliver inquiry units for MYP Spanish and Global Perspectives, applying the IB MYP framework to foster critical thinking and international mindedness.",
        "job2_title": "Spanish Language Teacher", "job2_desc1": "Plan and deliver Spanish curriculum for over 80 preparatory and 9th grade students (A1-A2 Level).",
        "job2_desc2": "Develop interactive educational resources (+30) using H5P and HTML/CSS, achieving notable improvement in student engagement.",
        "job2_desc3": "Lead the organization of cultural events such as Language Day to promote multilingualism in the school community.",
        "job2_desc4": "Actively collaborate in the preparation and logistics for the center's accreditation as an official DELE examination venue.",
        "job3_title": "Communication & Intercultural World Teacher", "job3_desc1": "Teach English to over 120 secondary school students, achieving measurable improvement in communicative competencies (A1-B2 Levels).",
        "job3_desc2": "Implement formative and summative assessment systems, using LMS platforms to optimize student feedback.",
        "job3_desc3": "Tutor and guide a cross-curricular environmental project, integrating language learning objectives with ecological awareness.",
        "job4_title": "Spanish and English Teacher", "job4_desc1": "Adapt language curriculum for primary and secondary school to a 'place-based education' approach, connecting learning with the local cultural and natural environment.",
        "education_title": "Education", "edu1_title": "IB Certificate in Teaching and Learning", "edu2_title": "Specialization Diploma in International Education",
        "edu3_title": "Master's degree in Teaching Spanish (ELE)", "edu4_title": "Bachelor of Education in Spanish and Foreign Languages",
        "skills_title": "Key Skills", "skills_soft_title": "Soft Skills", "skill_adaptability": "Adaptability", "skill_empathy": "Empathy & Patience",
        "skill_cultural": "Cross-cultural awareness", "skill_teamwork": "Teamwork", "skill_resilience": "Resilience",
        "skill_proactiveness": "Proactiveness", "skill_creativity": "Creativity", "skills_tech_title": "Technologies & Platforms",
        "languages_title": "Languages", "lang_spanish": "Spanish", "lang_spanish_level": "Native", "lang_english": "English", "lang_english_level": "C1 Advanced",
        "lang_french": "French", "lang_french_level": "B2 Upper Intermediate", "lang_turkish": "Turkish", "lang_turkish_level": "A1 Beginner",
        "print_name": "SERGIO URIBE GUINARD", "job1_location": "UWC Thailand | Thalang, Thailand 🇹🇭",
        "job2_location": "Tarsus American College | Tarsus, Türkiye 🇹🇷", "job3_location": "Colegio Alvernia Bilingüe | Bogotá, Colombia 🇨🇴",
        "job4_location": "Vicariato Apostólico de Inírida | Guainía, Colombia 🇨🇴", "edu1_location": "Universidad Camilo José Cela | Spain 🇪🇸",
        "edu2_location": "Universidad Camilo José Cela | Spain 🇪🇸", "edu3_location": "Universidad de Sevilla | Spain 🇪🇸",
        "edu4_location": "Universidad Pedagógica Nacional | Colombia 🇨🇴", "read_more": "Read more", "read_less": "Read less",
        "loading_language": "Loading language...", "last_updated": "Last updated:", "back_to_top": "Back to top",
        "focus_mode": "Focus mode", "high_contrast": "High contrast"
    },
    es: {
        "nav_profile": "Perfil", "nav_experience": "Experiencia", "nav_education": "Formación", "nav_skills": "Habilidades", "nav_languages": "Idiomas",
        "print_btn_text": "PDF", "contact_btn_text": "Información de Contacto", "contact_title": "Información de Contacto",
        "contact_location_label": "Ubicación", "contact_email_label": "Correo", "contact_phone_spain_label": "Teléfono (España)",
        "contact_phone_thailand_label": "Teléfono (Tailandia)", "linkedin_btn_text": "Ver Perfil LinkedIn",
        "profile_title": "Perfil Profesional", "profile_approach_title": "Enfoque Holístico de Enseñanza",
        "profile_text": "Educador de idiomas con trayectoria internacional y especialización en el marco del IB. Me enfoco en diseñar experiencias de aprendizaje holísticas que integran tecnología, indagación y sensibilidad cultural. Apasionado por crear entornos inclusivos que fomenten la mentalidad internacional y la ciudadanía global, utilizando mis habilidades técnicas para desarrollar recursos interactivos que potencian la participación y el dominio del idioma.",
        "profile_international_title": "Experiencia Internacional", "profile_international_desc": "Enseñanza en múltiples países y culturas",
        "profile_values_title": "Valores Fundamentales", "profile_values_desc": "Educación basada en respeto, compasión e integridad",
        "profile_inclusive_title": "Aprendizaje Inclusivo", "profile_inclusive_desc": "Creando entornos culturalmente receptivos",
        "experience_title": "Experiencia Laboral", "job1_title": "Profesor de Español PAI y Perspectivas Globales",
        "job1_desc1": "Diseñar e impartir unidades de indagación para Español PAI y Perspectivas Globales, aplicando el marco del PAI del IB para fomentar el pensamiento crítico y la mentalidad internacional.",
        "job2_title": "Profesor de Lengua Española", "job2_desc1": "Planificar e impartir el currículo de español para más de 80 estudiantes de preparatoria y 9º grado (Nivel A1-A2).",
        "job2_desc2": "Desarrollar recursos didácticos interactivos (+30) utilizando H5P y HTML/CSS, logrando un aumento notable en la participación estudiantil.",
        "job2_desc3": "Liderar la organización de eventos culturales como el Día del Idioma para promover el multilingüismo en la comunidad escolar.",
        "job2_desc4": "Colaborar activamente en la preparación y logística para la acreditación del centro como sede oficial de exámenes DELE.",
        "job3_title": "Profesor de Comunicación y Mundo Intercultural", "job3_desc1": "Impartir clases de inglés a más de 120 estudiantes de secundaria, logrando una mejora medible en las competencias comunicativas (Niveles A1-B2).",
        "job3_desc2": "Implementar un sistema de evaluación formativa y sumativa, utilizando plataformas LMS para optimizar la retroalimentación a los estudiantes.",
        "job3_desc3": "Tutorizar y guiar un proyecto transversal sobre medio ambiente, integrando objetivos de aprendizaje del idioma con la conciencia ecológica.",
        "job4_title": "Profesor de Español e Inglés", "job4_desc1": "Adaptar el currículo de idiomas para primaria y secundaria a un enfoque de 'place-based education', conectando el aprendizaje con el entorno cultural y natural local.",
        "education_title": "Formación Académica", "edu1_title": "Certificado IB en Enseñanza y Aprendizaje", "edu2_title": "Diploma de Especialización en Educación Internacional",
        "edu3_title": "Máster en Enseñanza de Español (ELE)", "edu4_title": "Licenciatura en Educación de Español y Lenguas Extranjeras",
        "skills_title": "Habilidades Clave", "skills_soft_title": "Habilidades Pedagógicas e Interpersonales", "skill_adaptability": "Adaptabilidad Curricular",
        "skill_empathy": "Inteligencia Emocional", "skill_cultural": "Comunicación Intercultural", "skill_teamwork": "Colaboración Docente",
        "skill_resilience": "Resiliencia", "skill_proactiveness": "Iniciativa y Liderazgo", "skill_creativity": "Diseño de Materiales",
        "skills_tech_title": "Tecnologías Educativas y Desarrollo", "languages_title": "Idiomas", "lang_spanish": "Español", "lang_spanish_level": "Nativo",
        "lang_english": "Inglés", "lang_english_level": "C1 Avanzado", "lang_french": "Francés", "lang_french_level": "B2 Intermedio Alto",
        "lang_turkish": "Turco", "lang_turkish_level": "A1 Principiante", "print_name": "SERGIO URIBE GUINARD",
        "job1_location": "UWC Thailand | Thalang, Tailandia 🇹🇭", "job2_location": "Tarsus American College | Tarsus, Türkiye 🇹🇷",
        "job3_location": "Colegio Alvernia Bilingüe | Bogotá, Colombia 🇨🇴", "job4_location": "Vicariato Apostólico de Inírida | Guainía, Colombia 🇨🇴",
        "edu1_location": "Universidad Camilo José Cela | España 🇪🇸", "edu2_location": "Universidad Camilo José Cela | España 🇪🇸",
        "edu3_location": "Universidad de Sevilla | España 🇪🇸", "edu4_location": "Universidad Pedagógica Nacional | Colombia 🇨🇴",
        "read_more": "Ver más", "read_less": "Ver menos", "loading_language": "Cargando idioma...", "last_updated": "Última actualización:",
        "back_to_top": "Volver arriba", "focus_mode": "Modo enfoque", "high_contrast": "Alto contraste"
    },
    fr: {
        "nav_profile": "Profil", "nav_experience": "Expérience", "nav_education": "Formation", "nav_skills": "Compétences", "nav_languages": "Langues",
        "print_btn_text": "PDF", "contact_btn_text": "Informations de Contact", "contact_title": "Informations de Contact",
        "contact_location_label": "Localisation", "contact_email_label": "Email", "contact_phone_spain_label": "Téléphone (Espagne)",
        "contact_phone_thailand_label": "Téléphone (Thaïlande)", "linkedin_btn_text": "Voir le Profil LinkedIn",
        "profile_title": "Profil Professionnel", "profile_approach_title": "Approche pédagogique holistique",
        "profile_text": "Avec une expérience internationale dans l'enseignement des langues, je suis guidé par une approche holistique pour concevoir des leçons qui intègrent les dimensions sociales, émotionnelles, cognitives et culturelles de l'apprentissage. Inspiré par les valeurs de respect, de compassion et d'intégrité, je m'efforce de créer des environnements d'apprentissage inclusifs et culturellement adaptés qui célèbrent les connexions multiculturelles et favorisent un sens de la citoyenneté mondiale.",
        "experience_title": "Expérience Professionnelle", "job1_title": "Enseignant d'Espagnol et de Perspectives Mondiales du PEI",
        "job1_desc1": "Concevoir et dispenser des unités d'enquête pour l'espagnol PEI et les Perspectives Mondiales, en appliquant le cadre PEI de l'IB pour favoriser la pensée critique et la mentalité internationale.",
        "job2_title": "Professeur de Langue Espagnole", "job2_desc1": "Planifier et dispenser le curriculum d'espagnol pour plus de 80 étudiants de préparation et de 9e année (Niveau A1-A2).",
        "job2_desc2": "Développer des ressources éducatives interactives (+30) en utilisant H5P et HTML/CSS, obtenant une amélioration notable de l'engagement étudiant.",
        "job2_desc3": "Diriger l'organisation d'événements culturels comme la Journée des Langues pour promouvoir le multilinguisme dans la communauté scolaire.",
        "job2_desc4": "Collaborer activement à la préparation et à la logistique pour l'accréditation du centre comme lieu officiel d'examens DELE.",
        "job3_title": "Enseignant de Communication et Monde Interculturel", "job3_desc1": "Enseigner l'anglais à plus de 120 étudiants du secondaire, obtenant une amélioration mesurable des compétences communicatives (Niveaux A1-B2).",
        "job3_desc2": "Implémenter des systèmes d'évaluation formative et sommative, en utilisant des plateformes LMS pour optimiser la rétroaction aux étudiants.",
        "job3_desc3": "Tutorer et guider un projet environnemental interdisciplinaire, intégrant les objectifs d'apprentissage de la langue avec la conscience écologique.",
        "job4_title": "Professeur d'Espagnol et d'Anglais", "job4_desc1": "Adapter le curriculum de langues pour le primaire et le secondaire à une approche d'éducation basée sur le lieu, connectant l'apprentissage avec l'environnement culturel et naturel local.",
        "education_title": "Formation", "edu1_title": "Certificat de l'IB en Enseignement et Apprentissage", "edu2_title": "Diplôme de Spécialisation en Éducation Internationale",
        "edu3_title": "Master en Enseignement de l'Espagnol (ELE)", "edu4_title": "Licence en Éducation de l'Espagnol et des Langues Étrangères",
        "skills_title": "Compétences Clés", "skills_soft_title": "Compétences Interpersonnelles", "skill_adaptability": "Adaptabilité",
        "skill_empathy": "Empathie et Patience", "skill_cultural": "Conscience interculturelle", "skill_teamwork": "Travail d'équipe",
        "skill_resilience": "Résilience", "skill_proactiveness": "Proactivité", "skill_creativity": "Créativité",
        "skills_tech_title": "Technologies et Plateformes", "languages_title": "Langues", "lang_spanish": "Espagnol", "lang_spanish_level": "Natif",
        "lang_english": "Anglais", "lang_english_level": "C1 Avancé", "lang_french": "Français", "lang_french_level": "B2 Intermédiaire Supérieur",
        "lang_turkish": "Turc", "lang_turkish_level": "A1 Débutant", "job1_location": "UWC Thailand | Thalang, Thaïlande 🇹🇭",
        "job2_location": "Tarsus American College | Tarsus, Türkiye 🇹🇷", "job3_location": "Colegio Alvernia Bilingüe | Bogotá, Colombie 🇨🇴",
        "job4_location": "Vicariato Apostólico de Inírida | Guainía, Colombie 🇨🇴", "edu1_location": "Universidad Camilo José Cela | Espagne 🇪🇸",
        "edu2_location": "Universidad Camilo José Cela | Espagne 🇪🇸", "edu3_location": "Universidad de Sevilla | Espagne 🇪🇸",
        "edu4_location": "Universidad Pedagógica Nacional | Colombie 🇨🇴", "read_more": "Lire la suite", "read_less": "Lire moins",
        "loading_language": "Chargement de la langue...", "last_updated": "Dernière mise à jour:", "back_to_top": "Retour en haut",
        "focus_mode": "Mode focus", "high_contrast": "Contraste élevé"
    },
    it: {
        "nav_profile": "Profilo", "nav_experience": "Esperienza", "nav_education": "Formazione", "nav_skills": "Competenze", "nav_languages": "Lingue",
        "print_btn_text": "PDF", "contact_btn_text": "Informazioni di Contatto", "contact_title": "Informazioni di Contatto",
        "contact_location_label": "Posizione", "contact_email_label": "Email", "contact_phone_spain_label": "Telefono (Spagna)",
        "contact_phone_thailand_label": "Telefono (Thailandia)", "linkedin_btn_text": "Visualizza Profilo LinkedIn",
        "profile_title": "Profilo Professionale", "profile_approach_title": "Approccio Olistico all'Insegnamento",
        "profile_text": "Con un background internazionale nell'insegnamento delle lingue, sono guidato da un approccio olistico per progettare lezioni che integrano le dimensioni sociali, emotive, cognitive e culturali dell'apprendimento. Ispirato dai valori di rispetto, compassione e integrità, mi impegno a creare ambienti di apprendimento inclusivi e culturalmente sensibili che celebrano le connessioni multiculturali e promuovono un senso di cittadinanza globale.",
        "experience_title": "Esperienza Lavorativa", "job1_title": "Insegnante di Spagnolo MYP e Prospettive Globali",
        "job1_desc1": "Progettare e condurre unità di indagine per Spagnolo MYP e Prospettive Globali, applicando il quadro MYP dell'IB per favorire il pensiero critico e la mentalità internazionale.",
        "job2_title": "Insegnante di Lingua Spagnola", "job2_desc1": "Pianificare e condurre il curriculum di spagnolo per oltre 80 studenti del corso preparatorio e del 9° anno (Livello A1-A2).",
        "job2_desc2": "Sviluppare risorse educative interattive (+30) utilizzando H5P e HTML/CSS, ottenendo un miglioramento notevole nell'impegno degli studenti.",
        "job2_desc3": "Guidare l'organizzazione di eventi culturali come la Giornata delle Lingue per promuovere il multilinguismo nella comunità scolastica.",
        "job2_desc4": "Collaborare attivamente nella preparazione e logistica per l'accreditamento del centro come sede ufficiale di esami DELE.",
        "job3_title": "Insegnante di Comunicazione e Mondo Interculturale", "job3_desc1": "Insegnare inglese a oltre 120 studenti della scuola secondaria, ottenendo un miglioramento misurabile nelle competenze comunicative (Livelli A1-B2).",
        "job3_desc2": "Implementare sistemi di valutazione formativa e sommativa, utilizzando piattaforme LMS per ottimizzare il feedback agli studenti.",
        "job3_desc3": "Fare da tutor e guidare un progetto ambientale interdisciplinare, integrando gli obiettivi di apprendimento linguistico con la consapevolezza ecologica.",
        "job4_title": "Insegnante di Spagnolo e Inglese", "job4_desc1": "Adattare il curriculum linguistico per la scuola primaria e secondaria a un approccio di 'educazione basata sul luogo', collegando l'apprendimento con l'ambiente culturale e naturale locale.",
        "education_title": "Formazione", "edu1_title": "Certificato IB in Insegnamento e Apprendimento", "edu2_title": "Diploma di Specializzazione in Educazione Internazionale",
        "edu3_title": "Master in Insegnamento dello Spagnolo (ELE)", "edu4_title": "Laurea in Educazione dello Spagnolo e Lingue Straniere",
        "skills_title": "Competenze Chiave", "skills_soft_title": "Competenze Trasversali", "skill_adaptability": "Adattabilità",
        "skill_empathy": "Empatia e Pazienza", "skill_cultural": "Consapevolezza interculturale", "skill_teamwork": "Lavoro di squadra",
        "skill_resilience": "Resilienza", "skill_proactiveness": "Proattività", "skill_creativity": "Creatività",
        "skills_tech_title": "Tecnologie e Piattaforme", "languages_title": "Lingue", "lang_spanish": "Spagnolo", "lang_spanish_level": "Madrelingua",
        "lang_english": "Inglese", "lang_english_level": "C1 Avanzato", "lang_french": "Francese", "lang_french_level": "B2 Intermedio Superiore",
        "lang_turkish": "Turco", "lang_turkish_level": "A1 Principiante", "job1_location": "UWC Thailand | Thalang, Thailandia 🇹🇭",
        "job2_location": "Tarsus American College | Tarsus, Türkiye 🇹🇷", "job3_location": "Colegio Alvernia Bilingüe | Bogotá, Colombia 🇨🇴",
        "job4_location": "Vicariato Apostólico de Inírida | Guainía, Colombia 🇨🇴", "edu1_location": "Universidad Camilo José Cela | Spagna 🇪🇸",
        "edu2_location": "Universidad Camilo José Cela | Spagna 🇪🇸", "edu3_location": "Universidad de Sevilla | Spagna 🇪🇸",
        "edu4_location": "Universidad Pedagógica Nacional | Colombia 🇨🇴", "read_more": "Leggi di più", "read_less": "Leggi meno",
        "loading_language": "Caricamento lingua...", "last_updated": "Ultimo aggiornamento:", "back_to_top": "Torna su", "focus_mode": "Modalità focus",
        "high_contrast": "Contrasto elevato"
    },
    th: {
        "nav_profile": "โปรไฟล์", "nav_experience": "ประสบการณ์", "nav_education": "การศึกษา", "nav_skills": "ทักษะ", "nav_languages": "ภาษา",
        "print_btn_text": "PDF", "contact_btn_text": "ข้อมูลติดต่อ", "contact_title": "ข้อมูลติดต่อ", "contact_location_label": "ที่อยู่",
        "contact_email_label": "อีเมล", "contact_phone_spain_label": "โทรศัพท์ (สเปน)", "contact_phone_thailand_label": "โทรศัพท์ (ไทย)",
        "linkedin_btn_text": "ดูโปรไฟล์ LinkedIn", "profile_title": "โปรไฟล์", "profile_approach_title": "แนวทางการสอนแบบองค์รวม",
        "profile_text": "ด้วยพื้นฐานด้านการศึกษาระหว่างประเทศในการสอนภาษา ข้าพเจ้าได้รับคำแนะนำจากแนวทางแบบองค์รวมในการออกแบบบทเรียนที่ผสมผสานมิติทางสังคม อารมณ์ ความรู้ความเข้าใจ และวัฒนธรรมของการเรียนรู้ ด้วยแรงบันดาลใจจากคุณค่าของความเคารพ ความเห็นอกเห็นใจ และความซื่อสัตย์ ข้าพเจ้ามุ่งมั่นที่จะสร้างสภาพแวดล้อมการเรียนรู้ที่ครอบคลุมและตอบสนองต่อวัฒนธรรม ที่เฉลิมฉลองการเชื่อมต่อทางวัฒนธรรมและส่งเสริมความเป็นพลเมืองโลก",
        "experience_title": "ประสบการณ์ทำงาน", "job1_title": "ครูสอนภาษาสเปนและมุมมองระดับโลก (MYP)",
        "job1_desc1": "ออกแบบและจัดส่งหน่วยการสืบสอบสำหรับภาษาสเปนและมุมมองระดับโลก (MYP) โดยใช้กรอบ MYP ของ IB เพื่อส่งเสริมการคิดเชิงวิพากษ์และจิตวิญญาณสากล",
        "job2_title": "ครูสอนภาษาสเปน", "job2_desc1": "วางแผนและจัดส่งหลักสูตรภาษาสเปนสำหรับนักเรียนมากกว่า 80 คนในระดับเตรียมความพร้อมและชั้นมัธยมศึกษาปีที่ 3 (ระดับ A1-A2)",
        "job2_desc2": "พัฒนาทรัพยากรการศึกษาที่โต้ตอบได้ (+30) โดยใช้ H5P และ HTML/CSS ซึ่งทำให้เกิดการปรับปรุงที่เห็นได้ชัดในการมีส่วนร่วมของนักเรียน",
        "job2_desc3": "นำการจัดกิจกรรมทางวัฒนธรรม เช่น วันภาษา เพื่อส่งเสริมการใช้หลายภาษาในชุมชนโรงเรียน",
        "job2_desc4": "ร่วมมืออย่างแข็งขันในการเตรียมและโลจิสติกส์สำหรับการรับรองศูนย์เป็นสถานที่สอบ DELE อย่างเป็นทางการ",
        "job3_title": "ครูสอนการสื่อสารและโลกต่างวัฒนธรรม", "job3_desc1": "สอนภาษาอังกฤษให้นักเรียนมัธยมศึกษามากกว่า 120 คน โดยบรรลุการปรับปรุงที่วัดได้ในความสามารถด้านการสื่อสาร (ระดับ A1-B2)",
        "job3_desc2": "ดำเนินการระบบการประเมินแบบสร้างสรรค์และสรุป โดยใช้แพลตฟอร์ม LMS เพื่อเพิ่มประสิทธิภาพการให้ข้อเสนอแนะแก่นักเรียน",
        "job3_desc3": "เป็นที่ปรึกษาและแนะนำโครงการสิ่งแวดล้อมแบบข้ามหลักสูตร โดยรวมเป้าหมายการเรียนรู้ภาษาเข้ากับจิตสำนึกด้านสิ่งแวดล้อม",
        "job4_title": "ครูสอนภาษาสเปนและอังกฤษ", "job4_desc1": "ปรับหลักสูตรภาษาสำหรับโรงเรียนประถมศึกษาและมัธยมศึกษาให้เข้ากับแนวทางการศึกษาแบบ 'ตามสถานที่' โดยเชื่อมโยงการเรียนรู้กับสิ่งแวดล้อมทางวัฒนธรรมและธรรมชาติในท้องถิ่น",
        "education_title": "การศึกษา", "edu1_title": "ใบรับรอง IB ด้านการสอนและการเรียนรู้", "edu2_title": "ประกาศนียบัตรเชี่ยวชาญพิเศษด้านการศึกษานานาชาติ",
        "edu3_title": "ปริญญาโทด้านการสอนภาษาสเปน (ELE)", "edu4_title": "ปริญญาตรีศึกษาศาสตร์บัณฑิต สาขาภาษาสเปนและภาษาต่างประเทศ",
        "skills_title": "ทักษะหลัก", "skills_soft_title": "ทักษะทางสังคม", "skill_adaptability": "การปรับตัว",
        "skill_empathy": "ความเห็นอกเห็นใจและความอดทน", "skill_cultural": "ความตระหนักข้ามวัฒนธรรม", "skill_teamwork": "การทำงานเป็นทีม",
        "skill_resilience": "ความยืดหยุ่น", "skill_proactiveness": "ความกระตือรือร้น", "skill_creativity": "ความคิดสร้างสรรค์",
        "skills_tech_title": "เทคโนโลยีและแพลตฟอร์ม", "languages_title": "ภาษา", "lang_spanish": "สเปน", "lang_spanish_level": "ภาษาแม่",
        "lang_english": "อังกฤษ", "lang_english_level": "C1 ขั้นสูง", "lang_french": "ฝรั่งเศส", "lang_french_level": "B2 ขั้นกลางสูง",
        "lang_turkish": "ตุรกี", "lang_turkish_level": "A1 เริ่มต้น", "job1_location": "UWC Thailand | Thalang, Thailand 🇹🇭",
        "job2_location": "Tarsus American College | Tarsus, Türkiye 🇹🇷", "job3_location": "Colegio Alvernia Bilingüe | Bogotá, Colombia 🇨🇴",
        "job4_location": "Vicariato Apostólico de Inírida | Guainía, Colombia 🇨🇴", "edu1_location": "Universidad Camilo José Cela | Spain 🇪🇸",
        "edu2_location": "Universidad Camilo José Cela | Spain 🇪🇸", "edu3_location": "Universidad de Sevilla | Spain 🇪🇸",
        "edu4_location": "Universidad Pedagógica Nacional | Colombia 🇨🇴", "read_more": "อ่านเพิ่มเติม", "read_less": "อ่านน้อยลง",
        "loading_language": "กำลังโหลดภาษา...", "last_updated": "อัปเดตล่าสุด:", "back_to_top": "กลับไปด้านบน", "focus_mode": "โหมดโฟกัส",
        "high_contrast": "คอนทราสต์สูง"
    },
    tr: {
        "nav_profile": "Profil", "nav_experience": "Deneyim", "nav_education": "Eğitim", "nav_skills": "Yetenekler", "nav_languages": "Diller",
        "print_btn_text": "PDF", "contact_btn_text": "İletişim Bilgileri", "contact_title": "İletişim Bilgileri",
        "contact_location_label": "Konum", "contact_email_label": "E-posta", "contact_phone_spain_label": "Telefon (İspanya)",
        "contact_phone_thailand_label": "Telefon (Tayland)", "linkedin_btn_text": "LinkedIn Profilini Görüntüle",
        "profile_title": "Profil", "profile_approach_title": "Bütünsel Öğretim Yaklaşımı",
        "profile_text": "Dil eğitiminde uluslararası bir geçmişe sahip olarak, öğrenmenin sosyal, duygusal, bilişsel ve kültürel boyutlarını bütünleştiren dersler tasarlamak için bütünsel bir yaklaşımla yönlendiriliyorum. Saygı, şefkat ve dürüstlük değerlerinden ilham alarak, çok kültürlü bağlantıları kutlayan ve küresel vatandaşlık duygusunu teşvik eden kapsayıcı ve kültürel olarak duyarlı öğrenme ortamları yaratmaya çalışıyorum.",
        "experience_title": "İş Deneyimi", "job1_title": "MYP İspanyolca ve Küresel Perspektifler Öğretmeni",
        "job1_desc1": "MYP İspanyolca ve Küresel Perspektifler için araştırma birimlerini tasarladı ve sundu, eleştirel düşünmeyi ve uluslararası zihniyeti teşvik etmek için IB MYP çerçevesini uyguladı.",
        "job2_title": "İspanyolca Dil Öğretmeni", "job2_desc1": "80'den fazla hazırlık ve 9. sınıf öğrencisi için İspanyolca müfredatını planladı ve sundu (A1-A2 Seviye).",
        "job2_desc2": "H5P ve HTML/CSS kullanarak etkileşimli eğitim kaynakları (+30) geliştirdi, öğrenci katılımında kayda değer iyileşme sağladı.",
        "job2_desc3": "Okul topluluğunda çok dilliliği teşvik etmek için Dil Günü gibi kültürel etkinliklerin organizasyonuna öncülük etti.",
        "job2_desc4": "Merkezin resmi DELE sınav yeri olarak akreditasyonu için hazırlık ve lojistik konularında aktif olarak işbirliği yaptı.",
        "job3_title": "İletişim ve Kültürlerarası Dünya Öğretmeni", "job3_desc1": "120'den fazla ortaokul öğrencisine İngilizce öğretti, iletişimsel yeterliliklerde ölçülebilir iyileşme sağladı (A1-B2 Seviyeler).",
        "job3_desc2": "Öğrenci geri bildirimini optimize etmek için LMS platformlarını kullanarak formatif ve summatif değerlendirme sistemleri uyguladı.",
        "job3_desc3": "Dil öğrenme hedeflerini ekolojik farkındalıkla entegre eden disiplinlerarası bir çevre projesinde danışmanlık ve rehberlik yaptı.",
        "job4_title": "İspanyolca ve İngilizce Öğretmeni", "job4_desc1": "İlkokul ve ortaokul için dil müfredatını 'yer temelli eğitim' yaklaşımına uyarladı, öğrenmeyi yerel kültürel ve doğal çevreyle bağladı.",
        "education_title": "Eğitim", "edu1_title": "Öğretme ve Öğrenmede IB Sertifikası", "edu2_title": "Uluslararası Eğitimde Uzmanlık Diploması",
        "edu3_title": "İspanyolca Öğretimi Yüksek Lisans Derecesi (ELE)", "edu4_title": "İspanyolca ve Yabancı Diller Eğitimi Lisans Derecesi",
        "skills_title": "Temel Yetenekler", "skills_soft_title": "Sosyal Beceriler", "skill_adaptability": "Uyum Sağlama",
        "skill_empathy": "Empati ve Sabır", "skill_cultural": "Kültürlerarası farkındalık", "skill_teamwork": "Takım Çalışması",
        "skill_resilience": "Dayanıklılık", "skill_proactiveness": "Proaktiflik", "skill_creativity": "Yaratıcılık",
        "skills_tech_title": "Teknolojiler ve Platformlar", "languages_title": "Diller", "lang_spanish": "İspanyolca", "lang_spanish_level": "Anadil",
        "lang_english": "İngilizce", "lang_english_level": "C1 İleri", "lang_french": "Fransızca", "lang_french_level": "B2 Orta Üstü",
        "lang_turkish": "Türkçe", "lang_turkish_level": "A1 Başlangıç", "job1_location": "UWC Thailand | Thalang, Tayland 🇹🇭",
        "job2_location": "Tarsus American College | Tarsus, Türkiye 🇹🇷", "job3_location": "Colegio Alvernia Bilingüe | Bogotá, Kolombiya 🇨🇴",
        "job4_location": "Vicariato Apostólico de Inírida | Guainía, Kolombiya 🇨🇴", "edu1_location": "Universidad Camilo José Cela | İspanya 🇪🇸",
        "edu2_location": "Universidad Camilo José Cela | İspanya 🇪🇸", "edu3_location": "Universidad de Sevilla | İspanya 🇪🇸",
        "edu4_location": "Universidad Pedagógica Nacional | Kolombiya 🇨🇴", "read_more": "Devamını oku", "read_less": "Daha az oku",
        "loading_language": "Dil yükleniyor...", "last_updated": "Son güncelleme:", "back_to_top": "Başa dön", "focus_mode": "Odak modu",
        "high_contrast": "Yüksek kontrast"
    },
    zh: {
        "nav_profile": "个人资料", "nav_experience": "经历", "nav_education": "教育", "nav_skills": "技能", "nav_languages": "语言",
        "print_btn_text": "PDF", "contact_btn_text": "联系信息", "contact_title": "联系信息", "contact_location_label": "位置",
        "contact_email_label": "邮箱", "contact_phone_spain_label": "电话（西班牙）", "contact_phone_thailand_label": "电话（泰国）",
        "linkedin_btn_text": "查看LinkedIn档案", "profile_title": "个人资料", "profile_approach_title": "整体教学法",
        "profile_text": "凭借在语言教育领域的国际背景，我以整体方法为指导，设计整合学习的社会、情感、认知和文化维度的课程。受到尊重、同情和正直价值观的启发，我努力创造包容和文化响应的学习环境，庆祝多元文化联系，培养全球公民意识。",
        "experience_title": "工作经历", "job1_title": "MYP西班牙语与全球视野教师",
        "job1_desc1": "设计并实施MYP西班牙语和全球视野的探究单元，运用IB MYP框架培养批判性思维和国际思维。",
        "job2_title": "西班牙语教师", "job2_desc1": "为80多名预科和九年级学生规划和实施西班牙语课程（A1-A2级）。",
        "job2_desc2": "使用H5P和HTML/CSS开发互动教育资源（+30个），显著提高学生参与度。",
        "job2_desc3": "领导组织语言日等文化活动，促进学校社区的多语言发展。",
        "job2_desc4": "积极参与中心作为官方DELE考试场所认证的筹备和后勤工作。",
        "job3_title": "沟通与跨文化世界教师", "job3_desc1": "为120多名中学生教授英语，在交际能力方面取得可衡量的改善（A1-B2级）。",
        "job3_desc2": "实施形成性和总结性评估系统，使用LMS平台优化学生反馈。",
        "job3_desc3": "指导跨课程环境项目，将语言学习目标与生态意识相结合。",
        "job4_title": "西班牙语和英语教师", "job4_desc1": "将中小学语言课程调整为'基于地方的教育'方法，将学习与当地文化和自然环境联系起来。",
        "education_title": "教育背景", "edu1_title": "IB教学证书", "edu2_title": "国际教育专业文凭",
        "edu3_title": "西班牙语教学硕士学位（ELE）", "edu4_title": "西班牙语和外语教育学士",
        "skills_title": "主要技能", "skills_soft_title": "软技能", "skill_adaptability": "适应性", "skill_empathy": "同理心和耐心",
        "skill_cultural": "跨文化意识", "skill_teamwork": "团队合作", "skill_resilience": "抗压能力",
        "skill_proactiveness": "积极主动", "skill_creativity": "创造力", "skills_tech_title": "技术与平台",
        "languages_title": "语言", "lang_spanish": "西班牙语", "lang_spanish_level": "母语", "lang_english": "英语",
        "lang_english_level": "C1 高级", "lang_french": "法语", "lang_french_level": "B2 中高级", "lang_turkish": "土耳其语",
        "lang_turkish_level": "A1 初级", "job1_location": "UWC Thailand | Thalang, Thailand 🇹🇭", "job2_location": "Tarsus American College | Tarsus, Türkiye 🇹🇷",
        "job3_location": "Colegio Alvernia Bilingüe | Bogotá, Colombia 🇨🇴", "job4_location": "Vicariato Apostólico de Inírida | Guainía, Colombia 🇨🇴",
        "edu1_location": "Universidad Camilo José Cela | Spain 🇪🇸", "edu2_location": "Universidad Camilo José Cela | Spain 🇪🇸",
        "edu3_location": "Universidad de Sevilla | Spain 🇪🇸", "edu4_location": "Universidad Pedagógica Nacional | Colombia 🇨🇴",
        "read_more": "阅读更多", "read_less": "阅读更少", "loading_language": "正在加载语言...", "last_updated": "最后更新：",
        "back_to_top": "返回顶部", "focus_mode": "专注模式", "high_contrast": "高对比度"
    }
};